// <auto-generated />
using System;
using CryptoApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525094232_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CryptoApp.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CryptoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsTriggered")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("ThresholdUsd")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime?>("TriggeredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CryptoId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("CryptoApp.Models.PriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Change24hPercent")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("CryptoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("PriceEur")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("PriceUsd")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CryptoId", "RecordedAt");

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("CryptoApp.Models.TrackedCrypto", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("TrackedCryptos");

                    b.HasData(
                        new
                        {
                            Id = "bitcoin",
                            IsActive = true,
                            Name = "Bitcoin",
                            Symbol = "BTC"
                        },
                        new
                        {
                            Id = "ethereum",
                            IsActive = true,
                            Name = "Ethereum",
                            Symbol = "ETH"
                        },
                        new
                        {
                            Id = "cardano",
                            IsActive = true,
                            Name = "Cardano",
                            Symbol = "ADA"
                        },
                        new
                        {
                            Id = "dogecoin",
                            IsActive = true,
                            Name = "Dogecoin",
                            Symbol = "DOGE"
                        },
                        new
                        {
                            Id = "solana",
                            IsActive = true,
                            Name = "Solana",
                            Symbol = "SOL"
                        },
                        new
                        {
                            Id = "ripple",
                            IsActive = true,
                            Name = "Ripple",
                            Symbol = "XRP"
                        });
                });

            modelBuilder.Entity("CryptoApp.Models.Alert", b =>
                {
                    b.HasOne("CryptoApp.Models.TrackedCrypto", "Crypto")
                        .WithMany("Alerts")
                        .HasForeignKey("CryptoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crypto");
                });

            modelBuilder.Entity("CryptoApp.Models.PriceHistory", b =>
                {
                    b.HasOne("CryptoApp.Models.TrackedCrypto", "Crypto")
                        .WithMany("PriceHistories")
                        .HasForeignKey("CryptoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crypto");
                });

            modelBuilder.Entity("CryptoApp.Models.TrackedCrypto", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("PriceHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
